version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student
      MYSQL_USER: mck0506
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: mysql
    volumes:
      - D:/Docker/volume/mysql_28:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456